// Public surface of @agent-custody/receipts. Framework adapters live on subpaths, ./sdk/<framework>, because they import optional peers.
export { AUTHORIZATION_PREDICATE_TYPE, buildAuthorizationStatement } from "./receipt.ts";
export type { AuthorizationBundle, AuthorizationPredicate, AuthorizationStatement } from "./receipt.ts";
export type { GatewayOptions } from "./gateway.ts";
export { buildRequest, restUpstream } from "./rest.ts";
export { openExporter, otlpExporter, spanFor } from "./otel.ts";
export { hecEvent, splunkExporter } from "./splunk.ts";
export { GRANT_HEADER, grantHeader, parseGrantHeader, serveHttp } from "./gateway-http.ts";
export { A2A_CARD_PATH, A2A_RECEIPT_METADATA_KEY, A2A_STREAM_META_KEY, a2aUpstream, fetchAgentCard, serveA2a, textOf } from "./a2a.ts";
export { deliverMail, founderNote, PortalStore, portalHandler, readSession, sendFollowUps, servePortal, signSession, stripeRequest, verifyStripeSignature } from "./portal.ts";
export type { MailOptions, OAuthOptions, PortalOptions, PortalUser, Profile, RunningPortal, StripeOptions } from "./portal.ts";
export type { HttpGatewayOptions, RunningHttpGateway } from "./gateway-http.ts";
export type { A2aServerOptions, AgentCard, ResolvedCard, RunningA2aServer } from "./a2a.ts";
export { exportLog, formatExport } from "./log-export.ts";
export type { ExportOptions, ExportResult } from "./log-export.ts";
export { fileBackend, importLogFile, PostgresLog, PostgresTenancy, RateLimiter } from "./log-store.ts";
export type { AuditEntry, Plan, QuotaState } from "./log-store.ts";
export { PLAN_QUOTAS, PLANS } from "./log-store.ts";
export { connectSigner, fetchLogKeys, localSigner, serveSigner, signerHandler } from "./signer.ts";
export type { KeyDocument, RemoteSignerOptions, RetiredKey, RunningSigner, Signer, SignerServerOptions } from "./signer.ts";
export { bothCheckpoints, dirCheckpoints, postgresCheckpoints } from "./checkpoints.ts";
export { adminRoutes, welcomeSheet } from "./log-admin.ts";
export { fetchWitnessKeys, Witness } from "./witness.ts";
export { checkLog, formatLogCheck } from "./log-check.ts";
export type { LogCheck, LogCheckOptions, LogCheckResult } from "./log-check.ts";
export type { WitnessOptions, WitnessOutcome, WitnessedCheckpoint } from "./witness.ts";
export type { AuditOptions } from "./verify.ts";
export type { AdminOptions } from "./log-admin.ts";
export type { Checkpoint, CheckpointStore } from "./checkpoints.ts";
export type { AppendResult, LogBackend, PostgresLike, PostgresLogOptions, RateLimitOptions, Tenant, TokenRecord } from "./log-store.ts";
export type { OtelConfig, OtlpOptions, ReceiptExporter } from "./otel.ts";
export type { SplunkConfig, SplunkOptions } from "./splunk.ts";
export type { IssuerOptions } from "./issue.ts";
export type { RestOptions, UpstreamClient } from "./rest.ts";
export * from "./config.ts";
export * from "./crypto.ts";
export * from "./delegation.ts";
export * from "./gateway.ts";
export * from "./issue.ts";
export * from "./log.ts";
export * from "./log-sink.ts";
export * from "./policy.ts";
export * from "./receipt.ts";
export * from "./verify.ts";
export * from "./sdk/index.ts";
export * from "./sidecar.ts";
export * from "./upstream.ts";
export * from "./retention.ts";
